name: GithNote
url: http://RogerioDosSantos.github.io
baseurl: /GithNote
#url: http://127.0.0.1:4000
#baseurl: /

description: 
avatar: 
disqus: 
google_analytics: UA-63348203-1
githnote-categories:
  Blog:
    display-style: post
    menu-position: -1
    header-position: 0
    foot-position: -1
githnote-sites:
  Github:
    link: https://github.com/RogerioDosSantos
    display-style: socialMedia
    position: 0
markdown: kramdown
highlighter: pygments
permalink: /:title/
version: v1.0.0
sass:
  sass_dir: _scss
  style: :expanded
gems:
  - jemoji
  - jekyll-sitemap
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
